### ISSUE TITLE
Change logic for BGV modulus switching in the AUTO* modes

### ISSUE THREAD

**Issue by yspolyakov** [openfheorg/openfhe-development#148]
https://gitlab.com/palisade/palisade-development/-/issues/365

**Comment by sarojaduality** [comment]
We decided not to implement this change because:

- It does not make sense for FlexibleAutoExt because the logic of choosing moduli in this mode depends on the rescaling to occur, and the for the ciphertext noise scaling degree to always be 2.
- It does not make sense for CKKS because we have to keep track of arbitrarily large floating-point scaling factors.

Given the above, to implement this change, we have to create BGV-specific logic for the modes FIXEDAUTO and FLEXIBLEAUTO, which makes the code unnecessarily complicated and more difficult to debug without a significant performance increase. We prefer the BGV code to be as similar as possible to CKKS, unless there are significant gains to be made from having scheme-specific code.
