### ISSUE TITLE
Duplicated Bugs in Scheme Switching

### ISSUE THREAD

**Issue by Maokami** [openfheorg/openfhe-development#522]
Hi everyone,

I've noticed that the bugs previously addressed in PR #415 ([patch](https://github.com/openfheorg/openfhe-development/pull/415/files#diff-5ec18c4139ac1f1f4c2bf3e60a12aec1839b7b96a3d10fe3e05a3f18b26b8cf4)) and #424 ([patch](https://github.com/openfheorg/openfhe-development/pull/424/files#diff-5ec18c4139ac1f1f4c2bf3e60a12aec1839b7b96a3d10fe3e05a3f18b26b8cf4)) has appeared in the [ckksrns-schemeswitching.cpp](https://github.com/openfheorg/openfhe-development/blob/main/src/pke/lib/scheme/ckksrns/ckksrns-schemeswitching.cpp#L229-L240).

**Comment by Maokami** [comment]
And may I ask why the MAX_BITS_IN_WORD is defined to be 61, which is 3 less than the 64 bits typically available in an int64_t?

**Comment by andreea-alexandru** [comment]
The referenced code is for the plaintext encoding done separately in scheme switching due to the need of encoding complex values; this is only required for the decoding matrix, which does not reach the limits for which the above patches were created. The patches were applied for consistency in [#527](https://github.com/openfheorg/openfhe-development/pull/527).
