### ISSUE TITLE
MultiHopPreTest Fails with BGV moduli estimates in FixedAuto

### ISSUE THREAD

**Issue by sarojaduality** [openfheorg/openfhe-development#94]
Some MULTIHOP_PRE_TESTs fail at times with the new moduli estimates in FixedAuto. The moduli estimates are located in bgvrns-parametergeneration.cpp. As a workaround, we currently estimate the keySwitchingNoise to use numPrimes + 1, resulting in larger moduli than necessary. This test fails when we use numPrimes.

**Comment by sararv22** [comment]
This bug was with an older version of the MultiHopPRE unittest file that was not updated and the PRE changes weren't in OpenFHE yet. Verified the tests to pass with the new PRE changes when changing the KeySwitchingNoise to numPrimes. Will create a PR to update the code in the dev branch to change it back to numPrimes.
